### ISSUE TITLE
Printer Efficiency only works on Misc Jobs

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#107]
I forgot to publish this card, the printer efficiency skill on HSkills only works for misc jobs, please change it so that this applies to misc AND criminal jobs, thank you.

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/140362488/1b71805f-e3d1-4734-8ba9-9d3f49bb2168)

**Comment by relz999** [comment]
fixed so that PreMoneyPrinterLooted hook looks for the skill in the Misc tree. Now pays out when a criminal job.
