### ISSUE TITLE
"Coin Pusher" music plays around the map

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#115]
**Title of the Bug**
"Coin Pusher" music plays around the map

**Description**
The music from "coin pusher" plays all around the map, this is exceptionally annoying for players. Doesn't look great on the server for quality either.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Not sure how to _directly_ reproduce, but when the music is prompted to play it can be heard all around mainstreet and most areas of the map (see evidence below).

**Expected Behavior**
Music should play in a reasonable range, e.g. only in the Casino.

**Actual Behavior**
See below.

**Evidence**

https://imgur.com/a/leBjkuZ

https://imgur.com/a/CcC1sku

**Comment by relz999** [comment]
Reduced the volume of the machine by 50%. The entity uses a 3d sound which has a fade, tested a few combinations and reducing volume ultimately solved this, an alternative would be to switch to normal emitsound with volume parameter
