### ISSUE TITLE
Org tag disappears after server restarts

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#116]
**Title of the Bug**
Org tag disappears after server restarts

**Description**
Org tags that appear in gang names reset to a question mark after every server restart.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Set an org tag in /org
2. Restart server
3. Org tag will appear as a question mark

**Expected Behavior**
Org tags should save and only change when a player does so intentionally

**Actual Behavior**
Org tags reset when the server restarts

**Evidence**
(If possible, please put any screenshots or videos)

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/140362488/4a8eb4a3-9c6d-4082-8ba7-5af76204a839)

^ Org tag has been set to a symbol every day since the server launched :(

**Comment by relz999** [comment]
Updated character set  to utf8mb4 and collate to utf8mb4_unicode_ci

Ꝟ due to its character set not saving and was changed to a "?". Once the character set and collate was updated to support the character is no longer a ?
