### ISSUE TITLE
Token shop extra props not working

### ISSUE THREAD

**Issue by DarkXFast** [civilnetworks-projects/DarkRP_Public_Development#117]
**Title of the Bug**
Token shop extra props not working

**Description**
The extra props on the token menu don't get added to the total amount of props that someone can have.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Buy +5 props from the token menu.
2. Look at your total props

**Expected Behavior**
The extra props should be added to the player's total prop.
Normal props you get = 40
Amethyst VIP = +75
token props = +5/each
Should add up to 130 props but it's 120.

**Actual Behavior**
The extra props don't get added to the player's total prop.

**Evidence**

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/19753158/37f98a49-2981-4a42-b3e6-96e3615ff3f5)

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/19753158/e7f386d9-b6e5-4562-9497-5a151ca9bde1)

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/19753158/6d055ecb-d1b5-4b07-a61e-19c72ba8ac8f)

**Comment by relz999** [comment]
this is fixed by using CNTokens to get prop bonus values
