### ISSUE TITLE
Weapon refund tool refunds handcuffs as well

### ISSUE THREAD

**Issue by DarkXFast** [civilnetworks-projects/DarkRP_Public_Development#118]
**Title of the Bug**
Weapon refund tool refunds handcuff as well

**Description**
When you refund a falsely arrested player it also puts them back on cuffs when it's not supposed to do that. Should be very easy to fix just blacklist weapon_handcuffed

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Get a player who has a gun on them arrested.
2. Unarrest the player and then refund him using the weapon refund menu.

**Expected Behavior**
Only the weapon should be refunded not the cuffs.

**Actual Behavior**
Player gets refunded the lost weapon but also gets put on handcuffs.

**Evidence**

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/19753158/64545b02-1b83-46aa-bb49-5ba78041879a)

**Comment by relz999** [comment]
added weapon_handcuffed to blacklist so that it not refunded, rendering the player cuffed after getting their refund.
