### ISSUE TITLE
Log Additions

### ISSUE THREAD

**Issue by ellie00001** [civilnetworks-projects/DarkRP_Public_Development#119]
- Meth/Weed - drop amounts and value - for arrests, deaths and disconnects. In the style of 

"[Player] was killed and lost Xg of [drug], valued at £Y."

- Meth/weed - Entity destruction - in the style of

"[Player] destroyed [Player]'s meth_stove/meth crate/weed, valued at £X and received £Y*

**Comment by relz999** [comment]
kill logs with values already exists, the assumption now is that all that weed or meth drops.  We might need to add logs for picking up the weed or meth

**Comment by relz999** [comment]
i've added logs for picking up weed blocks and meth crates which will detail the value. Therefore if people are killed and then it gets picked up you can match the two up in the logs in case of RDM.

**Comment by relz999** [comment]
Logs added when weed or meth equipment is destroyed. Rather than make new section for enhanced meth addon, i just put it under Zeros Meth, it will show the entity name so it will be clear it is a pot or stove from the older addon.
