### ISSUE TITLE
Skill perks do not apply to crafted printers

### ISSUE THREAD

**Issue by ellie00001** [civilnetworks-projects/DarkRP_Public_Development#121]
**Title of the Bug**
Skill tree perks do not apply to crafted printers

**Description**
Skill tree perks that improve printer efficiency do not apply to printers crafted from F4 crafting menu.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Have printer skills unlocked.
2. Craft printers from F4 menu.

**Expected Behavior**
(What was supposed to happen?)

Cooler and battery times should be extended.

**Actual Behavior**
(What actually happened?)

Printers act as if no perks are applied.

**Evidence**
(If possible, please put any screenshots or videos)

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/54053450/3046ac60-bc2b-4647-addf-8d8864d80137)

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/54053450/c70af63d-0e91-4875-b5b4-7621fe52631d)

**Comment by relz999** [comment]
Resolved, logic set when crafting to apply skill perks.
