### ISSUE TITLE
Add compatibility to the entity refund tool for Zero's GrowOp and HEconomy

### ISSUE THREAD

**Issue by DarkXFast** [civilnetworks-projects/DarkRP_Public_Development#125]
![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/19753158/92c4053e-d929-44d1-97c2-01da3842393d)

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/19753158/e3a532c4-15b5-4482-aa69-73ebbac3b517)

Will make it so head moderators won't have to contact admin+ for money refund.

**Comment by relz999** [comment]
Updated Kadmin entity refund to support HEconomy and Zeros Weedfarm
