### ISSUE TITLE
Jewelry Store Visual Bug

### ISSUE THREAD

**Issue by ellie00001** [civilnetworks-projects/DarkRP_Public_Development#127]
**Title of the Bug**
Jewelry Store Visual Bug

**Description**
Fix jewelry store display cases text. Right now the text becomes invisible depending on the background. See image below:

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. View text in display case from different angles

**Expected Behavior**
Text should be clear and easy to read.

**Actual Behavior**
Visual bug/glitch hides text.

**Evidence**

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/54053450/0b44c529-c2b8-4c89-a178-0afc5c1fbcad)

**Comment by relz999** [comment]
Re-enabled background and moved text above cabinets to give better visibility.
