### ISSUE TITLE
Move scavenging and cooking to levels, rather than skills

### ISSUE THREAD

**Issue by ellie00001** [civilnetworks-projects/DarkRP_Public_Development#131]
"Encourages people to scavenge and play chef to level up, and rewards those who do with better quality food. Maybe suggest these two skills at least be merged (and for scavenging to apply to all jobs), because one is basically useless without the other when you can't use level 15 ingredients if you are not max cooking, and if you are max cooking you can not get higher level ingredients to make use of it. This would however lead to one or two vacant skills."

Need to consider new skills

**Comment by ventz-lgtm** [comment]
Won't do since replacing vcraft with masterchef
