### ISSUE TITLE
Banpd command can be bypassed by Chief of Police vote

### ISSUE THREAD

**Issue by ellie00001** [civilnetworks-projects/DarkRP_Public_Development#137]
**Title of the Bug**
Banpd command can be bypassed by Chief of Police vote

**Description**
If someone is banned from PD jobs, they can still start a vote to become Chief of Police, allowing them to successfully become PD

**Comment by relz999** [comment]
new cloak_ban_commands did not list TEAM_CHIEF_OF_POLICE as a PD job. I've updated this and is now live on the server.
