### ISSUE TITLE
+HP Token upgrades/Skill tree not computing correctly

### ISSUE THREAD

**Issue by ellie00001** [civilnetworks-projects/DarkRP_Public_Development#138]
**Title of the Bug**
+HP Token upgrades/Skill tree not computing correctly

**Description**
Player that submitted bug has all HP skills from criminal tree unlocked, as well as +10HP and +25HP token upgrades. Player comments that when they started unlocking the +HP on Misc tree, it affected their upgraded base criminal HP. 

**Evidence**

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/54053450/9c2739ab-a90c-4b87-ac7b-42952317d069)

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/54053450/1a4b3e19-df8b-427a-be72-7ae4804e3066)

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/54053450/b04110e8-71f8-468e-8098-7e60ad9d074d)

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/54053450/d2541b1f-dc52-4adb-a8ec-79984cbda5a0)

Old HP, before unlocking +HP on Misc tree - 

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/54053450/3f3d7caa-1433-4c1a-bfab-5737bb8a0874)

New HP - 

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/54053450/23dc12b8-8ff4-4ec3-ae82-9953c756c3f6)

**Comment by relz999** [comment]
Highest skill achieved is applied from any tree for both HP++ and Armor++
