### ISSUE TITLE
Advanced Dupe 2 Ghosted Props Bug

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#14]
**Title of the Bug**
Advanced Dupe 2 Ghosted Props Bug

**Description**
When switching from the advanced dupe 2 tool to another tool, the outline of a dupe you were placing will remain, this will not dissappear until you reopen the tool. You cannot get this to stop happening once you've opened a dupe.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Open the advanced dupe tool
2. Select any dupe from your saved dupes (or copy a new one)
3. Do not place it down, switch to a different tool.

**Expected Behavior**
The ghosted / preview props disappear.

**Actual Behavior**
The ghosted props remain, as stated above

**Evidence**
[If possible, please put any screenshots or videos]
https://imgur.com/a/qyb5MFd

**Comment by AnthonyFuller** [comment]
Occurs with any toolgun that shows ghosted props (the jewellery addon one comes to mind, I've accidentally equipped this before).

**Comment by cloakical** [comment]
Might try uploading the latest version of advdupe2 to see if it fixes it.

**Comment by cloakical** [comment]
Unlikely to be fixed any time soon, honestly. We have a significantly diffed version of advdupe2 and can't easily update it.
