### ISSUE TITLE
Getting all health perks puts you over the 155hp limit for basing

### ISSUE THREAD

**Issue by ellie00001** [civilnetworks-projects/DarkRP_Public_Development#146]
NMXD spawns with 160 health - making him ineligible to base per rules

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/54053450/c324fbda-a9a6-44f7-9cec-602e680112be)

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/54053450/a193b67f-63a5-4724-9c80-659258713896)

**Comment by ellie00001** [comment]
@coolioo1 need basing HP rule changed from 155 to 160 - all server perks (token etc) plus having civilnetworks in your name puts you at 160 HP

**Comment by relz999** [comment]
As mentioned this is working as designed.
