### ISSUE TITLE
Simple Chem menu entities show as unavailable, even when your job is Chemist

### ISSUE THREAD

**Issue by ellie00001** [civilnetworks-projects/DarkRP_Public_Development#151]
![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/54053450/ce3a923b-db66-4231-abb5-9b6968f1cea9)

**Comment by relz999** [comment]
I believe this issue is something we won't take any further action on. The items can be purchased and only happens if you go to entities menu after changing job without closing and reopening the F4 menu
