### ISSUE TITLE
PD Doors to be alarmed

### ISSUE THREAD

**Issue by ellie00001** [civilnetworks-projects/DarkRP_Public_Development#152]
Content team have decided to remove PD raid adverts - this means that we will need to configure an alarm system for PD doors.

Doors -
- PD Reception door - not main double doors, but door beside reception desk
- PD Balcony door
- PD Roof entry hatch

Could be a similar UI to Vault theft - with a message showing up in chat, or a pop-up on the right hand side - I would suggest an alarm sound to accompany this for enhanced RP, if possible.

This alarm should sound for lockpicking and door charges.

Armoury could also be alarmed. 

This is now a priority as rule change will be getting run past SA this week, hoping this can go live by Friday?

**Comment by relz999** [comment]
Updated Door breach to have hook to trigger and be used by ventz robbery system which will check if the doors are lockpicked or door breached and sound an alarm and alert all active PD and AOD that the PD has been breached and there is a raid. Same logic used as vault gold. I've also added door breaches to the logs.

@ellie00001  please let me know when I can put the change live , not sure if we need to tell people there is a rule change.

**Comment by relz999** [comment]
This has now been deployed to Live.
