### ISSUE TITLE
New territory bonuses aren't working

### ISSUE THREAD

**Issue by ellie00001** [civilnetworks-projects/DarkRP_Public_Development#154]
Crimson confirmed that the new perk for printer efficiency in small town doesn't work - other territories may be affected too

![Image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/54053450/88e87db1-d7ba-4e7a-b26a-ee78c99fc85e)

**Comment by relz999** [comment]
Hook added to Vorgs2 to calculate and payout bonus payment for territory printer bonus
