### ISSUE TITLE
Broken PD Contracts

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#16]
**Title of the Bug**
Broken PD Contracts

**Description**
Some of the HSkills contracts do not work. These two being the PD-based ones

>PD Protector: Kill three armed people in the PD.
>Printer Cleanup: Destroy 5 printers as PD.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Attempt to complete either contact, it will not work. Killing armed people in PD or destroying a printer as PD does not add to the contract, it will remain at 0.

**Expected Behavior**
Doing the appropriate actions adds one out of 3 / 5.

**Actual Behavior**
Actions do not contribute to the contracts.

**Evidence**
N/A

**Comment by relz999** [comment]
Both contracts was using HSkills:GetActiveSkillTree(v) and should have been HSkills:GetActiveSkillTree(ply)
