### ISSUE TITLE
Change PD raiding rules

### ISSUE THREAD

**Issue by CommanderSmith98** [civilnetworks-projects/DarkRP_Public_Development#161]
Allow raiding the PD without advertising PD raids. Even when the server had 40–50 players daily, people constantly complained about there being nothing to do and no crimes going on. This rule change is intended to make PD raiding more accessible, especially if you intend to raid the armoury or breaking people out. Right now, stealth-raiding the PD for any of those purposes is essentially out of the question when all the police come running. If the coming update brings players back, I think people desperately need more activities to engage in to prevent people from leaving out of boredom. The gold vault is the only activity that needs a global cooldown and alerting the PD, and it should be more worthwhile with the added risk. The armoury works just fine with an individual cooldown after having lock picked it and no other advert requirements. If people start farming the armoury too much - just increase the individual cooldown. I would also consider lowering the PD requirement by 1 or 2 for the various raids (gold vault, jewellery, armoury), because when there's fewer people on this content gets locked, giving the remaining players even less to do, which in turn encourages them to leave as well. If raiding the vault becomes too easy, I would suggest adding a vault door delay + alarm where the raiders need to wait a minute or so before the vault door opens after pressing the buttons, in order to give PD time to respond and make the vault more of a high risk/high reward activity.
-Umbrella

**Comment by ghost** [comment]
Closed due to this being a rule change not a feature.
