### ISSUE TITLE
Chemist F4 Entities Not Appearing

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#18]
**Title of the Bug**
Chemist F4 Entities Not Appearing

**Description**
The SimpleMeth equipment does not show up for Chemists in the F4 menu. In order to still place entities, players must show "unavailable items" at which point they can still spawn the meth. I am logging this here because multiple reports as well as tickets have been made, this is potentially confusing for new players.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
Unsure of how to replicate, this seemingly happens at random to various players.

**Expected Behavior**
"SimpleMeth" entities show up in the F4 menu entities for a Chemist, whilst on the job.

**Actual Behavior**
Players must show "unavailable items" at which point they can still spawn the meth. This happens whilst on the chemist job.

**Evidence**
(If possible, please put any screenshots or videos)

![Image](https://user-images.githubusercontent.com/140362488/261518565-e29600c7-9e91-4adc-97c9-6854f0295d61.png)

![Image](https://user-images.githubusercontent.com/140362488/261518588-41e41dbd-6fdb-4169-832c-df70aa2dabbb.png)

**Comment by HerrKvarkar** [comment]
Problem with VJobEditor, will need more debugging to find out why this is occurring.

**Comment by relz999** [comment]
From what I can see in testing, this is no longer an issue.

**Comment by relz999** [comment]
This is resolved.
