### ISSUE TITLE
PD Vault Door Doesn't Open

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#19]
**Title of the Bug**
PD Vault Door Doesn't Open

**Description**
The vault door inside of the PD doesn't open, this means that raiding the PD isn't possible at the moment.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
Attempt to open the vault door in PD, it will not open.

**Expected Behavior**
Door can open at the push of two buttons.

**Actual Behavior**
Door doesn't open.

**Evidence**
(If possible, please put any screenshots or videos)

**Comment by Freezgam03** [comment]
Will be fixed with next restart
