### ISSUE TITLE
Hack Phone Bugged

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#23]
**Title of the Bug**
Hack Phone Bugged

**Description**
The hack phone, given to covert thief and FBI is experiencing several bugs currently. For the most part it does not function as it used to, and requires a clear line of sight in order to hack keypads, players, etc. Players have reported that disabling the minimap fixes the issues with the hackphone.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Attempt to use the hackphone through props / a wall, on either a player or keypad.
2. The hackphone will not work unless you have a clear line of sight, and will hack the closest hackable rather than the one the user wants to target.

**Expected Behavior**
The hack phone should be able to hack through walls, and should target the hackable entity the player is looking at.

**Actual Behavior**
See above.

**Evidence**
(If possible, please put any screenshots or videos)

https://user-images.githubusercontent.com/140362488/261821057-5e6b0d38-ff54-4636-8154-2edb36729871.mp4

**Comment by Anna-cybers** [comment]
NO I'M NOT A FRAUDULENT PERSON! 
IM A ETHICAL HACKING PROFESSIONAL WHO RENDERS ONLINE (WHITE HAT) HACKING SUCH AS
💙FACEBOOK ACCOUNT RECOVERY
💙FACEBOOK ACCOUNT HACKING 
💙INSTAGRAM ACCOUNT RECOVERY 💜INSTAGRAM ACCOUNT HACKING 
💜SNAPCHAT / TIKTOK UNBAN 
💚INSTA-FB MESSAGE HACK
💙ONLINE MESSAGE HACKING 
💜WEBSITE HACKING 
💛CHEATING IN RELATIONSHIP HACK
💛LOST FUNDS RECOVERY (scammers payback) 

📥ANNA_CYBERWEB 0N INSTAGRAM 🕸️DONALDSONHARRY013@GMAIL.COM

How can I help you? SEND AN INBOX OR EMAIL ME FOR SWIFT RESPONSE 24/7
INSTAGRAM LINK https://www.instagram.com/p/Cxbd-lfNEX4/?igshid=MzRlODBiNWFlZA==

Whatsapp Hacking, Instagram Hacking, Remote Phone Access, Database Hacking, Website Hacking, Email Hacking, Snapchat Hacking, Twitter Hacking, Facebook Hacking, Tiktok Hacking, Wechat Hacking, Telegram Hacking. Automated System. Result within 48 hours.

Text on Instagram 📥ANNA_CYBERWEB

**Comment by Anna-cybers** [comment]
> **Title of the Bug**
> Hack Phone Bugged
> 
> **Description**
> The hack phone, given to covert thief and FBI is experiencing several bugs currently. For the most part it does not function as it used to, and requires a clear line of sight in order to hack keypads, players, etc. Players have reported that disabling the minimap fixes the issues with the hackphone.
> 
> **Steps to Reproduce**
> (Your goto way to recreate this bug.)
> 1. Attempt to use the hackphone through props / a wall, on either a player or keypad.
> 2. The hackphone will not work unless you have a clear line of sight, and will hack the closest hackable rather than the one the user wants to target.
> 
> **Expected Behavior**
> The hack phone should be able to hack through walls, and should target the hackable entity the player is looking at.
> 
> **Actual Behavior**
> See above.
> 
> **Evidence**
> (If possible, please put any screenshots or videos)
> 
> https://user-images.githubusercontent.com/140362488/261821057-5e6b0d38-ff54-4636-8154-2edb36729871.mp4
> 
> 

⚒️NO FREE SERVICE ⚒️

NO I'M NOT A FRAUDULENT PERSON! 
IM A ETHICAL HACKING PROFESSIONAL WHO RENDERS ONLINE (WHITE HAT) HACKING SUCH AS
💙FACEBOOK ACCOUNT RECOVERY
💙FACEBOOK ACCOUNT HACKING 
💙INSTAGRAM ACCOUNT RECOVERY 💜INSTAGRAM ACCOUNT HACKING 
💜SNAPCHAT / TIKTOK UNBAN 
💚INSTA-FB MESSAGE HACK
💙ONLINE MESSAGE HACKING 
💜WEBSITE HACKING 
💛CHEATING IN RELATIONSHIP HACK
💛LOST FUNDS RECOVERY (scammers payback) 

📥ANNA_CYBERWEB 0N INSTAGRAM 🕸️DONALDSONHARRY013@GMAIL.COM

How can I help you? SEND AN INBOX OR EMAIL ME FOR SWIFT RESPONSE 24/7
INSTAGRAM LINK https://www.instagram.com/p/Cxbd-lfNEX4/?igshid=MzRlODBiNWFlZA==

Whatsapp Hacking, Instagram Hacking, Remote Phone Access, Database Hacking, Website Hacking, Email Hacking, Snapchat Hacking, Twitter Hacking, Facebook Hacking, Tiktok Hacking, Wechat Hacking, Telegram Hacking. Automated System. Result within 48 hours.

Text on Instagram 📥ANNA_CYBERWEB

**Comment by relz999** [comment]
@HugestFella23  how do I reproduce this? https://medal.tv/games/garrys-mod/clips/1vJksPxhEyXTIf/d1337s4ZIBtx?invite=cr-MSxGM1ksMjY3MDMxMjMs

**Comment by HugestFella23** [comment]
> @HugestFella23 how do I reproduce this? https://medal.tv/games/garrys-mod/clips/1vJksPxhEyXTIf/d1337s4ZIBtx?invite=cr-MSxGM1ksMjY3MDMxMjMs

Enable the minimap, it's related to the VMinimap.

**Comment by relz999** [comment]
This is due to a known issue https://github.com/Facepunch/garrysmod-issues/issues/1404
A workaround provided has been applied to the vmap3 addon.
