### ISSUE TITLE
BanPD Command Doesn't Ban FBI

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#25]
**Title of the Bug**
BanPD Command Doesn't Ban FBI

**Description**
The BanPD Command doesn't ban people from the FBI job.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Ban someone (or yourself) from PD
2. Have them try to switch to a PD job
3. Police Officer, S.W.A.T etc. will be unavailable
4. Try switching to FBI, it will let you.

**Expected Behavior**
Target of the BanPD Command is banned from all PD related jobs.

**Actual Behavior**
FBI is not included in this.

**Evidence**
(If possible, please put any screenshots or videos)

**Comment by HugestFella23** [comment]
As an update to this issue, it appears that the BanPD command doesn't ban SWAT either. It essentially does not function at all.

**Comment by cloakical** [comment]
the config looks fine so I can only assume the `CC_BanJob` function is completely fucked. currently I am planning to port over `cloak_ban_commands` module from SCP-RP vwar as a fix.

**Comment by cloakical** [comment]
On server after restart

**Comment by HugestFella23** [comment]
BanPD command functions as it should, bans the user from PD and doesn't allow them to go back on any job in the category.
