### ISSUE TITLE
Health Kit sound plays over a big radius as well as out of view

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks-projects/DarkRP_Public_Development#29]
**Description**
If someone gets healed by the Health Kit, the sound that is played can be heard over a very big radius, and can be heard even if the player who is doing it is not in sight

**Steps to Reproduce**
Have someone heal someone e.g. at Fountain, then you stand in the small tunnel when going from Spawn to Main Street and it will play the sound as if you are standing right next to it

**Expected Behavior**
The sound would only play if you are near to prevent disturbance of other players doing other stuff

**Actual Behavior**
Plays as if it was played right on your own player and not from the player that is healing someone

**Comment by relz999** [comment]
Reduced sound level from 150 to 50 See link below for a reference list of values. This will mean you can only hear it within 5-10metres

https://wiki.facepunch.com/gmod/Enums/SNDLVL
