### ISSUE TITLE
Trashman can see players with trash on them through props / walls

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#36]
**Title of the Bug**
Trashman can see players with trash on them through props / walls

**Description**
Trashmen are able to see players through walls if they have trash on them. This also applies through props. This was apparently fixed by Cloak in the past, but isn't currently fixed on the server.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Play trashman
2. Look at a player with trash on them, this will show through a wall
3. This should also work with props

**Expected Behavior**
Trashmen shouldn't be able to see players through walls, even if they have trash on them.

**Actual Behavior**
Trashman can see players with trash on them through props / walls

**Evidence**
(If possible, please put any screenshots or videos)

![Image](https://user-images.githubusercontent.com/140362488/262787891-730ea186-f5c0-4f0d-b214-f4980d9560f1.png)

**Comment by relz999** [comment]
Updated code to not display unless there is line of sight.
