### ISSUE TITLE
Bounty System Regulation

### ISSUE THREAD

**Issue by coolioo1** [civilnetworks-projects/DarkRP_Public_Development#39]
- Remove bounty victim the from the bounty list for 15 minutes after completion
- Players can only place a bounty every 15 minutes
- If a bounty isn't completed in 30 minutes it's removed from the board

**Comment by relz999** [comment]
Changed made to store time
A) a player last placed a successful bounty
B) a player who has a bounty on them is successfully completed
C) the time a player has a bounty placed on them.

There are then 3 cooldown configuration settings to set the length of time, currently 15mins between placing hits, 15mins to place another hit on someone just killed for a bounty, and if a bounty is on a player for more than 30 mins it is removed.

Tested on Dev, no issues found
