### ISSUE TITLE
Armoury Lockpick Purchase Error

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#48]
**Title of the Bug**
Armoury Lockpick Purchase Error

**Description**
When buying an Armoury Lockpick from the shop NPC, you will be met with an error message (you still receive the lockpick)

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Go to the shop NPC and purchase an armoury lockpick
2. You will see an error message appear in console, you will still receive the lockpick.

**Expected Behavior**
Should not receive an error message

**Actual Behavior**
Players will be met with an error when purchasing the lockpick

**Evidence**
(If possible, please put any screenshots or videos)

[police_armory_locker] addons/police_armory_locker/lua/weapons/armory_lockpick/shared.lua:61: bad argument #1 to 'SetDeploySpeed' (number expected, got nil)
  1. SetDeploySpeed - [C]:-1
   2. unknown - addons/police_armory_locker/lua/weapons/armory_lockpick/shared.lua:61

**Comment by relz999** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1917043256  added to the resource file. Also fixed SetDeploySpeed error in Lua. This value doesn't seem to exist in the addon. Might be worth seeing if the latest version of the addon has any other fixes.
