### ISSUE TITLE
Replace Ballistic Jammer in Skilltree

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#49]
The Ballistic Jammer skills in the PD tree needs to be replaced with a different skill.

**Comment by relz999** [comment]
@HugestFella23  please update the card with the skill you wish to replace it with. If you need to chat about whats possible let me know.

**Comment by relz999** [comment]
On CC we had a skill called PD Loadout which gave you an extra gun depending on PD Job.

Light = "vguns_deagle",
Medium = "vguns_famas",
Heavy = "vguns_para"

**Comment by relz999** [comment]
@HugestFella23  @ellie00001  Can you please take a look at this. Need input before I can complete this.

**Comment by ellie00001** [comment]
@relz999 Rem approves, but I'm unsure on gun choice - hopefully need to make them "desirable"

**Comment by ellie00001** [comment]
Light - Deagle
- FBI Agent
- Police Officer

Medium - FAMAS
- Mechanical Officer
- Police Corporal
- Chief of Police
- SWAT
- SWAT Medic
- SWAT Sniper

Heavy - PARA
- Police Sergeant
- SWAT Juggernaut
- SWAT Team Leader

@relz999

**Comment by relz999** [comment]
Server updated will go live after restart
