### ISSUE TITLE
Allow the Chemist Equipment to be Physgunned

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#59]
Make it so chemist equipment is physgunnable, however, will not function if it is placed on a wall or is inverted. Kvarkar will carry over the system from the weed addon where it is unable to work when upside down.

**Comment by relz999** [comment]
Removed Pot, SPOT, and Stove from cgpp blacklist, added to share.lua files networkvar self:NetworkVar("Entity", 1,"owning_ent") so that ownership can be applied to enable phygunning.
