### ISSUE TITLE
Tactical Flashlight Bugged

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#61]
**Title of the Bug**
Tactical Flashlight Bugged

**Description**
The light from the tactical flashlight is angled upwards.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Turn on the flashlight
2. Light is angled upwards when it shouldn't be

**Expected Behavior**
Light from the flashlight should point directly forwards

**Actual Behavior**
See video below

**Evidence**
(If possible, please put any screenshots or videos)

https://imgur.com/a/7PBXljN

**Comment by cloakical** [comment]
changing this to critical as this is an insanely bad bug for new player experience

**Comment by relz999** [comment]
Tested and this issue doesn't seem directly related to the SWEP itself. works fine standalone there must be a conflict with another addon which is on DarkRP and not on SCP. Need to investigate further.

**Comment by relz999** [comment]
Believe this is a map issue and not an issue with the torch itself. https://developer.valvesoftware.com/wiki/Env_projectedtexture/fixes#Alternative_.22proper.22_Hammer_fix

@Freezgam03  - Can you assist and confirm if this is a map issue, please? the same code for the torch is run on MRP fine. when I try gm_flatgrass I also get odd behaviour with the torch different from the DarkRP map.
