### ISSUE TITLE
Warehouse reduced cooldown upgrade not functioning

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#62]
**Title of the Bug**
Warehouse reduced cooldown upgrade not functioning

**Description**
The "reduce cooldown" purchased for the warehouses do not work.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Purchase the reduced cooldown in a warehouse
2. This will not reduce the cooldown despite the confirmed purchase

**Expected Behavior**
Slight reduction of the warehouse cooldown if you have the upgrade

**Actual Behavior**
See above

**Evidence**
(If possible, please put any screenshots or videos)

**Comment by relz999** [comment]
Cannot reproduce the error. Purchased 2 warehouses, completed mission, tried again, got cool down, purchased 5min reduction, tried mission again and it was reduced by 300 seconds (5mins)
