### ISSUE TITLE
Warehouse cars broken

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#64]
**Title of the Bug**
Warehouse cars broken

**Description**
Players report that warehouse cars spawn covered in errors and don't function.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Attempt a car-based warehouse missions
2. Based on reports the car should spawn bugged and unable to be used

**Expected Behavior**
The car should function according to the mission, and work

**Actual Behavior**
See above

**Evidence**
(If possible, please put any screenshots or videos)

**Comment by AnthonyFuller** [comment]
Still an issue:
![image](https://github.com/civilnetworks-projects/DarkRP_Public_Development/assets/24512050/b197717c-c4ce-43b1-a2fa-abc96e875a2a)

(Note: I was a black market dealer while doing missions, but I was not on cocaine or anything, was using a car to get around)

**Comment by relz999** [comment]
Updated missions to use either the smart car or peel car which are on the server.
