### ISSUE TITLE
Bad crate spawns in warehouse missions

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#66]
**Title of the Bug**
Bad crate spawns in warehouse missions

**Description**
The crates in warehouse missions are reported as spawning in strange places around the map, e.g. on top of Fountain.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Hard to recreate, attempt a warehouse mission and check the spawns if possible.

**Expected Behavior**
Crate spawns should be in specific areas rather than in entirely random places, in order to prevent this issue.

**Actual Behavior**
Reports state that crates spawn in strange, hard to get to places.

**Evidence**
(If possible, please put any screenshots or videos)

**Comment by AnthonyFuller** [comment]
Some also spawn inside bases, i.e. the building to the left of the jewellery shop.

**Comment by HerrKvarkar** [comment]
@HugestFella23 Please type getpos in console for each crate so I have an idea of where they are

**Comment by AnthonyFuller** [comment]
Base next to jewellery shop:
- 2 normally spawn around here: `-1239.939331 -2838.956055 -131.968750`
- 1 normally spawns around here: `-1362.973999 -3157.263184 -131.968750`

Rough fountain position: `-1866.176514 -1643.937500 -143.968750`

**Comment by relz999** [comment]
Fixed bad spawn locations

1 Delivery spawn location
8 on foot delivery spawn locations
