### ISSUE TITLE
Warehouse selling mission bug

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#70]
**Title of the Bug**
Warehouse selling mission bug

**Description**
If a player dies during a warehouse selling missions, it will affect the value of the sell regardless of what job the player is on.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Start a warehouse selling mission
2. Have a player in your org die, on AOD / PD jobs
3. This will affect the selling mission, even though the jobs are not involved

**Expected Behavior**
Only criminal jobs assisting in the sell should affect it

**Actual Behavior**
All players in an org affect the sell, regardless of what job they're on.

**Evidence**
(If possible, please put any screenshots or videos)

**Comment by relz999** [comment]
If an org member is one of the below jobs it will not impact the sell price if they die during the sell mission

* The Flash
* AOD (should have god mode, but mentioned in bug text)
* PD
