### ISSUE TITLE
Printer Hitbox

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#82]
**Title of the Bug**
Printer Hitbox

**Description**
The Printer Hitbox only registers when shooting at the UI.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Shoot the printer in any area that doesn't have the UI
2. Shots won't connect despite the fact that they clearly should

**Expected Behavior**
N/A

**Actual Behavior**
See above

**Evidence**
(If possible, please put any screenshots or videos)

**Comment by relz999** [comment]
Check model and it has a perfectly fine hitbox. Add debug to the printer to output damage taken. I was able to shoot anywhere on the printer and it registered damage. There is not a bug.
