### ISSUE TITLE
Spawn Protection reaches jesusland

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#88]
**Title of the Bug**
Spawn Protection reaches jesusland

**Description**
The spawn protection reaches into jesusland, this makes some events hard to run (e.g. hunger games)

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Attempt to shoot in the area above a safe zone in jesusland
2. Bullets will be blocked due to protections
3.

**Expected Behavior**
This should only be in effect in spawn.

**Actual Behavior**
See above.

**Evidence**
(If possible, please put any screenshots or videos)

**Comment by relz999** [comment]
Kvarkar has configured new zones in the spawn room, and staff rooms to stop damage, therefore I have removed the block on gun usage within vguns within the spawn area. This will mean the reported bug will no longer occur in jesus land after restart
