### ISSUE TITLE
Decrease the range at which HEconomy Equipment can be heard

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#89]
HEconomy mining equipment can be heard from long distances. In the image below I'm able to hear the equipment from this distance (stopped sound multiple times)

![Image](https://user-images.githubusercontent.com/140362488/268117945-94117f94-614b-4860-bc02-0c0613f7d3b6.png)

![Image](https://user-images.githubusercontent.com/140362488/268117979-de3ce042-47b1-4b26-a980-1383fa3c8564.png)

**Comment by relz999** [comment]
added ENT.StartSoundLevel = 55 to the share.lua files of entities. This way if any need adjusting individually in future they can be. 55 is considered "home" noise level. https://wiki.facepunch.com/gmod/Enums/SNDLVL
