### ISSUE TITLE
Remove the infinite printer battery from the skill tree

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#97]
Infinite printer battery causes printers to blow up if someone goes AFK, please make it so that at 5/5 the battery lasts twice as long, rather than being infinite.

![Image](https://user-images.githubusercontent.com/140362488/268465689-4e9ee363-7f8a-4c5c-af01-ff1e36545a7d.png)

**Comment by RedSpeeds** [comment]
I dont see this as a bug personally. Its the responsibility of the player to keep the coolers running. Perhaps make the infinity battery a option that can be toggled instead?

**Comment by HugestFella23** [comment]
> I dont see this as a bug personally. Its the responsibility of the player to keep the coolers running. Perhaps make the infinity battery a option that can be toggled instead?

That just sounds pointless ,this is an oversight that many players have complained about. Even daring to go AFK will result in your printers blowing up 100% of the time. Whereas any player without the perk would simply lose out on profit if they went AFK, a player with this skill would lose their VIP printers. It's not avoidable either, since you need 5/5 in order to get SkullBreaker.
