### ISSUE TITLE
VCMiner USB Stick

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#99]
We're readding the VCminer USB Stick, it'll need to be modified to be compatible with terminals other than the mainframe.

**Comment by relz999** [comment]
Only compatible with mainframes, need to add support for all terminal types before releasing.

**Comment by relz999** [comment]
Updated Vcminer to work with other terminals. Requires testing by the content team. It is on the dev server please @HugestFella23  can you ask the team to try it out? 

Testing should be focused on the following.

1. USB stick connects to terminal.
2. Count down timer is visible with ease
3. Removing the USB works

There are no changes to the fundamental working of the USB, It is just making sure cosmetically it connects and can be removed.

**Comment by HugestFella23** [comment]
> Updated Vcminer to work with other terminals. Requires testing by the content team. It is on the dev server please @HugestFella23 can you ask the team to try it out?
> 
> Testing should be focused on the following.
> 
> 1. USB stick connects to terminal.
> 2. Count down timer is visible with ease
> 3. Removing the USB works
> 
> There are no changes to the fundamental working of the USB, It is just making sure cosmetically it connects and can be removed.

Will test this with Kvar today

**Comment by relz999** [comment]
This has now been added to live.
